server:
  port: 9010

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
      - id: routes-user-service
        uri: lb://user-service
        predicates: 
        - Path=/users/**,/roles/**,opersets/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: gateway-server